target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'Firebase'
  pod 'Google-Mobile-Ads-SDK'
end